import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
export type Language = "en" | "es";
const messages: Record<Language, Record<string, string>> = {
  en: {
    brand: "BORICUIR MEMORY",
    creator: "Creator",
    language: "Language",
    signIn: "Sign in",
    signOut: "Sign out",
    logoutTitle: "Sign out of your account?",
    logoutText: "You’ll need to sign in again to play online or update your profile.",
    cancel: "Cancel",
    connecting: "Connecting…",
    played: "played",
    won: "won",
    player: "Player",
    uniquePairs: "unique pairs",
    modeLeaderboard: "Top 3 leaderboard",
    topThreeHelp: "The best score recorded for each player in this game mode.",
    firstLeaderboardEntry: "Finish a signed-in game to claim the first position.",
    continueIn: "Continue",
    creatorExperience: "A game by Sexkúl",
    preparingGame: "Preparing all 80 illustrated pairs…",
    heroKicker: "Puerto Rican cuir culture, one pair at a time",
    heroTitle1: "Remember.",
    heroTitle2: "Match. Celebrate.",
    heroText:
      "Pick a mode, invite your people, and discover all 80 Boricuir pairs.",
    chooseMode: "Choose a game mode",
    modeHelp: "Each mode changes how you play and score.",
    popular: "Popular",
    localOpponents: "Local opponents",
    localHelp:
      "Mix people sharing this device with computer-controlled opponents.",
    humanPlayers: "Human players",
    numberBots: "Number of bots",
    none: "None",
    bot: "Bot",
    bots: "Bots",
    botDifficulty: "Bot difficulty",
    easy: "easy",
    medium: "medium",
    hard: "hard",
    mostlyRandom: "Mostly random",
    remembersSome: "Remembers some cards",
    sharpMemory: "Sharp memory",
    onlineOpponents: "Online opponents",
    onlineHelp: "Private rooms use real account players on separate devices.",
    onlinePlayers: "Players in online room",
    boardSize: "Board size",
    selectedGame: "Selected game",
    players: "Players",
    cards: "Cards",
    playOnline: "Play online",
    playLocally: "Play locally",
    pairs: "pairs",
    quick: "Quick",
    classic: "Classic",
    challenge: "Challenge",
    fullDeck: "Full Deck",
    sound: "Sound",
    settings: "Settings",
    gamePreferences: "Game preferences",
    audioSettings: "Audio settings",
    audioSettingsHelp: "Control the game music, sound effects, and volume.",
    languageSettings: "Language settings",
    languageHelp: "Choose the language used throughout the game.",
    backgroundMusic: "Background music",
    musicHelp: "Loop the Boricuir theme while you play.",
    musicVolume: "Music volume",
    soundEffects: "Sound effects",
    effectsHelp: "Clicks, matches, misses, warnings, and results.",
    effectsVolume: "Effects volume",
    testSound: "Test sound",
    close: "Close",
    welcomeBack: "Welcome back",
    createPlayer: "Create your player",
    signInHelp: "Sign in to create and join games on any device.",
    signupHelp: "Your free account keeps your player identity and game stats.",
    displayName: "Display name",
    email: "Email",
    password: "Password",
    pleaseWait: "Please wait…",
    createAccount: "Create account",
    newHere: "New here? Create an account",
    alreadyAccount: "Already have an account? Sign in",
    checkEmail: "Check your email to confirm your account, then sign in.",
    authFailed: "Authentication failed.",
    community: "Boricuir community",
    liveMultiplayer: "Live multiplayer",
    onlineTitle1: "Play together,",
    onlineTitle2: "wherever you are.",
    connectSupabase: "Connect Supabase first",
    supabaseHelp:
      "Run the included SQL file, then add your project URL and anon key to .env.",
    accountRequired: "An account is required",
    accountHelp: "Sign in once, then create or join rooms from any device.",
    signInOrCreate: "Sign in or create account",
    playingAs: "Playing as",
    online: "Online",
    hostGame: "Host a game",
    createRoom: "Create a room",
    createRoomHelp:
      "Uses the mode, board size, and online player count selected on the home screen.",
    creating: "Creating…",
    createPrivateRoom: "Create private room",
    invitation: "Have an invitation?",
    joinRoom: "Join a room",
    quickAction: "Quick action",
    joinPrivateRoom: "Join private room",
    joinHelp: "Enter the six-character room code shared by the host.",
    roomCode: "Room code",
    joining: "Joining…",
    joinGame: "Join game",
    joiningRoom: "Joining room…",
    roomUnavailable: "Room unavailable",
    roomMissing: "This room no longer exists.",
    returnHome: "Return home",
    privateRoom: "Private room",
    waitingPlayers: "Waiting for players",
    shareCode: "Share this room code",
    copyCode: "Copy code",
    ready: "ready",
    waitingForPlayer: "Waiting for player",
    onlineNow: "Online now",
    connectingDots: "Connecting…",
    host: "Host",
    notReady: "Not ready",
    imReady: "I’m ready",
    waitingAnother: "Waiting for another player",
    waitingReady: "Waiting until everyone is ready",
    startGame: "Start game",
    memoryPreview: "Memory Rush preview",
    yourTurn: "Your turn",
    isPlaying: "is playing",
    previewEnds: "Cards flip when the preview ends",
    checkingPair: "Checking the pair…",
    chooseTwo: "Choose two cards",
    liveUpdates: "Cards update live on every device",
    matches: "Matches",
    moves: "Moves",
    timeLeft: "Time left",
    time: "Time",
    lives: "Lives",
    progress: "Progress",
    points: "points",
    away: "Away",
    memorize: "Memorize the board!",
    devicesBegin: "Every device begins together.",
    cardsFlip: "Cards will flip over when the preview ends.",
    thinking: "is thinking…",
    difficulty: "difficulty",
    playing: "Playing",
    currentStreak: "Current streak",
    newGame: "New game",
    mode: "mode",
    point: "point",
    matchedCard: "Matched card",
    revealedCard: "Card face revealed",
    hiddenCard: "Hidden card",
    timesUp: "Time’s up!",
    noChances: "No chances left!",
    boardComplete: "Board complete!",
    wins: "wins!",
    tied: "tied!",
    gameModes: "Game modes",
    playAgain: "Play again",
    of: "of",
    onlineComplete: "Online match complete",
    gameOver: "Game over",
    returnLobby: "Return to online lobby",
    cardRevealed: "Card revealed",
    tapReturn: "Tap anywhere to return to the board",
    enlargedArt: "Enlarged Boricuir card artwork",
    quitTitle: "Quit this game?",
    quitText: "Your current progress will be lost.",
    stayGame: "Keep playing",
    quitGame: "Quit game",
  },
  es: {
    brand: "BORICUIR MEMORY",
    creator: "Creador",
    language: "Idioma",
    signIn: "Iniciar sesión",
    signOut: "Cerrar sesión",
    logoutTitle: "¿Cerrar sesión?",
    logoutText: "Tendrás que iniciar sesión nuevamente para jugar en línea o actualizar tu perfil.",
    cancel: "Cancelar",
    connecting: "Conectando…",
    played: "jugadas",
    won: "ganadas",
    player: "Jugador",
    uniquePairs: "pares únicos",
    modeLeaderboard: "Tabla de líderes — Top 3",
    topThreeHelp: "La mejor puntuación registrada de cada jugador en este modo.",
    firstLeaderboardEntry: "Termina una partida con tu cuenta para ocupar la primera posición.",
    continueIn: "Continuar",
    creatorExperience: "Un juego de Sexkúl",
    preparingGame: "Preparando los 80 pares ilustrados…",
    heroKicker: "Cultura cuir puertorriqueña, un par a la vez",
    heroTitle1: "Recuerda.",
    heroTitle2: "Combina. Celebra.",
    heroText:
      "Elige un modo, invita a tu gente y descubre los 80 pares Boricuir.",
    chooseMode: "Elige un modo de juego",
    modeHelp: "Cada modo cambia la forma de jugar y acumular puntos.",
    popular: "Popular",
    localOpponents: "Oponentes locales",
    localHelp:
      "Combina personas en este dispositivo con oponentes controlados por la computadora.",
    humanPlayers: "Jugadores humanos",
    numberBots: "Cantidad de bots",
    none: "Ninguno",
    bot: "Bot",
    bots: "Bots",
    botDifficulty: "Dificultad de bots",
    easy: "fácil",
    medium: "medio",
    hard: "difícil",
    mostlyRandom: "Mayormente al azar",
    remembersSome: "Recuerda algunas cartas",
    sharpMemory: "Memoria precisa",
    onlineOpponents: "Oponentes en línea",
    onlineHelp:
      "Las salas privadas usan personas reales en dispositivos separados.",
    onlinePlayers: "Jugadores en la sala",
    boardSize: "Tamaño del tablero",
    selectedGame: "Juego seleccionado",
    players: "Jugadores",
    cards: "Cartas",
    playOnline: "Jugar en línea",
    playLocally: "Jugar local",
    pairs: "pares",
    quick: "Rápido",
    classic: "Clásico",
    challenge: "Desafío",
    fullDeck: "Baraja completa",
    sound: "Sonido",
    settings: "Configuraciones",
    gamePreferences: "Preferencias del juego",
    audioSettings: "Configuración de audio",
    audioSettingsHelp: "Controla la música, los efectos de sonido y el volumen.",
    languageSettings: "Configuración de idioma",
    languageHelp: "Elige el idioma utilizado en todo el juego.",
    backgroundMusic: "Música de fondo",
    musicHelp: "Reproduce el tema Boricuir mientras juegas.",
    musicVolume: "Volumen de música",
    soundEffects: "Efectos de sonido",
    effectsHelp: "Clics, pares, fallos, avisos y resultados.",
    effectsVolume: "Volumen de efectos",
    testSound: "Probar sonido",
    close: "Cerrar",
    welcomeBack: "Bienvenidx de nuevo",
    createPlayer: "Crea tu jugador",
    signInHelp:
      "Inicia sesión para crear y unirte a juegos desde cualquier dispositivo.",
    signupHelp: "Tu cuenta gratuita conserva tu identidad y estadísticas.",
    displayName: "Nombre visible",
    email: "Correo electrónico",
    password: "Contraseña",
    pleaseWait: "Espera…",
    createAccount: "Crear cuenta",
    newHere: "¿Eres nuevx? Crea una cuenta",
    alreadyAccount: "¿Ya tienes cuenta? Inicia sesión",
    checkEmail:
      "Revisa tu correo para confirmar tu cuenta y luego inicia sesión.",
    authFailed: "No se pudo autenticar.",
    community: "Comunidad Boricuir",
    liveMultiplayer: "Multijugador en vivo",
    onlineTitle1: "Jueguen juntxs,",
    onlineTitle2: "estén donde estén.",
    connectSupabase: "Primero conecta Supabase",
    supabaseHelp:
      "Ejecuta el archivo SQL incluido y añade la URL y clave anónima a .env.",
    accountRequired: "Se requiere una cuenta",
    accountHelp:
      "Inicia sesión una vez y crea o únete a salas desde cualquier dispositivo.",
    signInOrCreate: "Iniciar sesión o crear cuenta",
    playingAs: "Jugando como",
    online: "En línea",
    hostGame: "Organiza un juego",
    createRoom: "Crear una sala",
    createRoomHelp:
      "Usa el modo, tamaño y cantidad de jugadores en línea elegidos en inicio.",
    creating: "Creando…",
    createPrivateRoom: "Crear sala privada",
    invitation: "¿Tienes una invitación?",
    joinRoom: "Unirse a una sala",
    quickAction: "Acción rápida",
    joinPrivateRoom: "Unirse a sala privada",
    joinHelp:
      "Ingresa el código de seis caracteres compartido por la persona anfitriona.",
    roomCode: "Código de sala",
    joining: "Entrando…",
    joinGame: "Unirse al juego",
    joiningRoom: "Entrando a la sala…",
    roomUnavailable: "Sala no disponible",
    roomMissing: "Esta sala ya no existe.",
    returnHome: "Volver al inicio",
    privateRoom: "Sala privada",
    waitingPlayers: "Esperando jugadores",
    shareCode: "Comparte este código",
    copyCode: "Copiar código",
    ready: "listos",
    waitingForPlayer: "Esperando al jugador",
    onlineNow: "En línea ahora",
    connectingDots: "Conectando…",
    host: "Anfitrión",
    notReady: "No listo",
    imReady: "Estoy listx",
    waitingAnother: "Esperando otro jugador",
    waitingReady: "Esperando que todxs estén listos",
    startGame: "Comenzar juego",
    memoryPreview: "Vista previa Memory Rush",
    yourTurn: "Tu turno",
    isPlaying: "está jugando",
    previewEnds: "Las cartas se voltean al terminar la vista previa",
    checkingPair: "Verificando el par…",
    chooseTwo: "Elige dos cartas",
    liveUpdates: "Las cartas se actualizan en vivo en cada dispositivo",
    matches: "Pares",
    moves: "Movidas",
    timeLeft: "Tiempo restante",
    time: "Tiempo",
    lives: "Vidas",
    progress: "Progreso",
    points: "puntos",
    away: "Ausente",
    memorize: "¡Memoriza el tablero!",
    devicesBegin: "Todos los dispositivos comienzan juntos.",
    cardsFlip: "Las cartas se voltearán al terminar la vista previa.",
    thinking: "está pensando…",
    difficulty: "dificultad",
    playing: "Jugando",
    currentStreak: "Racha actual",
    newGame: "Juego nuevo",
    mode: "modo",
    point: "punto",
    matchedCard: "Carta emparejada",
    revealedCard: "Carta revelada",
    hiddenCard: "Carta oculta",
    timesUp: "¡Se acabó el tiempo!",
    noChances: "¡No quedan oportunidades!",
    boardComplete: "¡Tablero completado!",
    wins: "¡gana!",
    tied: "¡empatan!",
    gameModes: "Modos de juego",
    playAgain: "Jugar de nuevo",
    of: "de",
    onlineComplete: "Partida en línea completada",
    gameOver: "Fin del juego",
    returnLobby: "Volver a la sala en línea",
    cardRevealed: "Carta revelada",
    tapReturn: "Toca cualquier lugar para volver al tablero",
    enlargedArt: "Arte ampliado de la carta Boricuir",
    quitTitle: "¿Salir del juego?",
    quitText: "Perderás el progreso actual.",
    stayGame: "Seguir jugando",
    quitGame: "Salir del juego",
  },
};
type Value = {
  language: Language;
  setLanguage: (value: Language) => void;
  t: (key: string) => string;
};
const Context = createContext<Value | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() =>
    localStorage.getItem("boricuir-language") === "es" ? "es" : "en"
  );
  useEffect(() => {
    localStorage.setItem("boricuir-language", language);
    document.documentElement.lang = language;
  }, [language]);
  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => messages[language][key] ?? messages.en[key] ?? key,
    }),
    [language]
  );
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useLanguage() {
  const value = useContext(Context);
  if (!value)
    throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
